'use client';
/**
 * Re-exports all @talon-sandbox/react components as Client Components.
 *
 * MDX pages import from this barrel so that useState/useEffect hooks inside
 * the library components are in a client boundary. Without 'use client' here,
 * Next.js App Router would treat them as RSC and throw an error when it
 * encounters useState in a component.
 */
export {
  Button,
  Input,
  Select,
  Textarea,
  Switch,
  Segmented,
  Card,
  Panel,
  Badge,
  StatusBadge,
  Table,
  KV,
  Tabs,
  EmptyState,
  Dialog,
  Drawer,
  toast,
  ToastViewport,
  ProgressBar,
  CodeBlock,
  PageHeader,
  FilterBar,
  StatCard,
  StatCardGrid,
  ResRow,
  TerminalChrome,
  RecordingPlayer,
  FormSection,
  FormGrid,
  MemberRow,
  CmdKOverlay,
  TweaksPanel,
  THEME_SWATCHES,
  SandboxStateBar,
  DEFAULT_STATE_ORDER,
  DEFAULT_STATE_COLORS,
  LoginLayout,
  type TweaksTheme,
  type TweaksMode,
  type TweaksDensity,
  type TweaksFont,
  type TweaksLang,
  // Phase 2 — new components from feat/component-library-v2
  FormField,
  Checkbox,
  Radio,
  RadioGroup,
  NumberInput,
  Slider,
  MultiSelect,
  FormItem,
  TablePagination,
  DataTable,
  Combobox,
  type FormFieldProps,
  type CheckboxProps,
  type RadioProps,
  type RadioGroupProps,
  type RadioGroupOption,
  type NumberInputProps,
  type SliderProps,
  type MultiSelectProps,
  type MultiSelectOption,
  type FormItemProps,
  type TablePaginationProps,
  type DataTableProps,
  type DataTableServerState,
  type ComboboxProps,
  type ComboboxOption,
  type ComboboxSize,
  type AnyFieldApi,
} from '@talon-sandbox/react';
