// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/.dumi/pages/index.tsx?type=frontmatter';
import { frontmatter as fm1, toc as t1 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/getting-started/installation.en-US.md?type=frontmatter';
import { demoIndex as dmi1 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/getting-started/installation.en-US.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/getting-started/dark-mode.en-US.md?type=frontmatter';
import { demoIndex as dmi2 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/getting-started/dark-mode.en-US.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/getting-started/theming.en-US.md?type=frontmatter';
import { demoIndex as dmi3 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/getting-started/theming.en-US.md?type=demo-index';
import { frontmatter as fm4, toc as t4 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/getting-started/installation.md?type=frontmatter';
import { demoIndex as dmi4 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/getting-started/installation.md?type=demo-index';
import { frontmatter as fm5, toc as t5 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/getting-started/dark-mode.md?type=frontmatter';
import { demoIndex as dmi5 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/getting-started/dark-mode.md?type=demo-index';
import { frontmatter as fm6, toc as t6 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/getting-started/theming.md?type=frontmatter';
import { demoIndex as dmi6 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/getting-started/theming.md?type=demo-index';
import { frontmatter as fm7, toc as t7 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/typography.en-US.md?type=frontmatter';
import { demoIndex as dmi7 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/typography.en-US.md?type=demo-index';
import { frontmatter as fm8, toc as t8 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/elevation.en-US.md?type=frontmatter';
import { demoIndex as dmi8 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/elevation.en-US.md?type=demo-index';
import { frontmatter as fm9, toc as t9 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/overview.en-US.md?type=frontmatter';
import { demoIndex as dmi9 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/overview.en-US.md?type=demo-index';
import { frontmatter as fm10, toc as t10 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/spacing.en-US.md?type=frontmatter';
import { demoIndex as dmi10 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/spacing.en-US.md?type=demo-index';
import { frontmatter as fm11, toc as t11 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/motion.en-US.md?type=frontmatter';
import { demoIndex as dmi11 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/motion.en-US.md?type=demo-index';
import { frontmatter as fm12, toc as t12 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/color.en-US.md?type=frontmatter';
import { demoIndex as dmi12 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/color.en-US.md?type=demo-index';
import { frontmatter as fm13, toc as t13 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/typography.md?type=frontmatter';
import { demoIndex as dmi13 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/typography.md?type=demo-index';
import { frontmatter as fm14, toc as t14 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/elevation.md?type=frontmatter';
import { demoIndex as dmi14 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/elevation.md?type=demo-index';
import { frontmatter as fm15, toc as t15 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/overview.md?type=frontmatter';
import { demoIndex as dmi15 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/overview.md?type=demo-index';
import { frontmatter as fm16, toc as t16 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/spacing.md?type=frontmatter';
import { demoIndex as dmi16 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/spacing.md?type=demo-index';
import { frontmatter as fm17, toc as t17 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/motion.md?type=frontmatter';
import { demoIndex as dmi17 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/motion.md?type=demo-index';
import { frontmatter as fm18, toc as t18 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/color.md?type=frontmatter';
import { demoIndex as dmi18 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/color.md?type=demo-index';
import { frontmatter as fm19, toc as t19 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/index.en-US.md?type=frontmatter';
import { demoIndex as dmi19 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/index.en-US.md?type=demo-index';
import { frontmatter as fm20, toc as t20 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/index.md?type=frontmatter';
import { demoIndex as dmi20 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/index.md?type=demo-index';
import { frontmatter as fm21, toc as t21 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Accordion/index.md?type=frontmatter';
import { demoIndex as dmi21 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Accordion/index.md?type=demo-index';
import { frontmatter as fm22, toc as t22 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Alert/index.md?type=frontmatter';
import { demoIndex as dmi22 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Alert/index.md?type=demo-index';
import { frontmatter as fm23, toc as t23 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/AlertDialog/index.md?type=frontmatter';
import { demoIndex as dmi23 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/AlertDialog/index.md?type=demo-index';
import { frontmatter as fm24, toc as t24 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Avatar/index.md?type=frontmatter';
import { demoIndex as dmi24 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Avatar/index.md?type=demo-index';
import { frontmatter as fm25, toc as t25 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Badge/index.md?type=frontmatter';
import { demoIndex as dmi25 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Badge/index.md?type=demo-index';
import { frontmatter as fm26, toc as t26 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Banner/index.md?type=frontmatter';
import { demoIndex as dmi26 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Banner/index.md?type=demo-index';
import { frontmatter as fm27, toc as t27 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Breadcrumb/index.md?type=frontmatter';
import { demoIndex as dmi27 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Breadcrumb/index.md?type=demo-index';
import { frontmatter as fm28, toc as t28 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Button/index.md?type=frontmatter';
import { demoIndex as dmi28 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Button/index.md?type=demo-index';
import { frontmatter as fm29, toc as t29 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Calendar/index.md?type=frontmatter';
import { demoIndex as dmi29 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Calendar/index.md?type=demo-index';
import { frontmatter as fm30, toc as t30 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Card/index.md?type=frontmatter';
import { demoIndex as dmi30 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Card/index.md?type=demo-index';
import { frontmatter as fm31, toc as t31 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Checkbox/index.md?type=frontmatter';
import { demoIndex as dmi31 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Checkbox/index.md?type=demo-index';
import { frontmatter as fm32, toc as t32 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/CodeBlock/index.md?type=frontmatter';
import { demoIndex as dmi32 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/CodeBlock/index.md?type=demo-index';
import { frontmatter as fm33, toc as t33 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Combobox/index.md?type=frontmatter';
import { demoIndex as dmi33 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Combobox/index.md?type=demo-index';
import { frontmatter as fm34, toc as t34 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/CommandPalette/index.md?type=frontmatter';
import { demoIndex as dmi34 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/CommandPalette/index.md?type=demo-index';
import { frontmatter as fm35, toc as t35 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/ContextMenu/index.md?type=frontmatter';
import { demoIndex as dmi35 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/ContextMenu/index.md?type=demo-index';
import { frontmatter as fm36, toc as t36 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/DataTable/index.md?type=frontmatter';
import { demoIndex as dmi36 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/DataTable/index.md?type=demo-index';
import { frontmatter as fm37, toc as t37 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/DateRangePicker/index.md?type=frontmatter';
import { demoIndex as dmi37 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/DateRangePicker/index.md?type=demo-index';
import { frontmatter as fm38, toc as t38 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Dialog/index.md?type=frontmatter';
import { demoIndex as dmi38 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Dialog/index.md?type=demo-index';
import { frontmatter as fm39, toc as t39 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Divider/index.md?type=frontmatter';
import { demoIndex as dmi39 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Divider/index.md?type=demo-index';
import { frontmatter as fm40, toc as t40 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Drawer/index.md?type=frontmatter';
import { demoIndex as dmi40 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Drawer/index.md?type=demo-index';
import { frontmatter as fm41, toc as t41 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/DropdownMenu/index.md?type=frontmatter';
import { demoIndex as dmi41 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/DropdownMenu/index.md?type=demo-index';
import { frontmatter as fm42, toc as t42 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/EmptyState/index.md?type=frontmatter';
import { demoIndex as dmi42 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/EmptyState/index.md?type=demo-index';
import { frontmatter as fm43, toc as t43 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/FileUpload/index.md?type=frontmatter';
import { demoIndex as dmi43 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/FileUpload/index.md?type=demo-index';
import { frontmatter as fm44, toc as t44 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/FilterChip/index.md?type=frontmatter';
import { demoIndex as dmi44 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/FilterChip/index.md?type=demo-index';
import { frontmatter as fm45, toc as t45 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Flex/index.md?type=frontmatter';
import { demoIndex as dmi45 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Flex/index.md?type=demo-index';
import { frontmatter as fm46, toc as t46 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/FormField/index.md?type=frontmatter';
import { demoIndex as dmi46 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/FormField/index.md?type=demo-index';
import { frontmatter as fm47, toc as t47 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Grid/index.md?type=frontmatter';
import { demoIndex as dmi47 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Grid/index.md?type=demo-index';
import { frontmatter as fm48, toc as t48 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Input/index.md?type=frontmatter';
import { demoIndex as dmi48 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Input/index.md?type=demo-index';
import { frontmatter as fm49, toc as t49 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/InputGroup/index.md?type=frontmatter';
import { demoIndex as dmi49 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/InputGroup/index.md?type=demo-index';
import { frontmatter as fm50, toc as t50 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Kbd/index.md?type=frontmatter';
import { demoIndex as dmi50 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Kbd/index.md?type=demo-index';
import { frontmatter as fm51, toc as t51 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/KV/index.md?type=frontmatter';
import { demoIndex as dmi51 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/KV/index.md?type=demo-index';
import { frontmatter as fm52, toc as t52 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Label/index.md?type=frontmatter';
import { demoIndex as dmi52 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Label/index.md?type=demo-index';
import { frontmatter as fm53, toc as t53 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/List/index.md?type=frontmatter';
import { demoIndex as dmi53 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/List/index.md?type=demo-index';
import { frontmatter as fm54, toc as t54 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Menubar/index.md?type=frontmatter';
import { demoIndex as dmi54 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Menubar/index.md?type=demo-index';
import { frontmatter as fm55, toc as t55 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/MultiSelect/index.md?type=frontmatter';
import { demoIndex as dmi55 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/MultiSelect/index.md?type=demo-index';
import { frontmatter as fm56, toc as t56 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/NavMenu/index.md?type=frontmatter';
import { demoIndex as dmi56 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/NavMenu/index.md?type=demo-index';
import { frontmatter as fm57, toc as t57 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/NumberInput/index.md?type=frontmatter';
import { demoIndex as dmi57 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/NumberInput/index.md?type=demo-index';
import { frontmatter as fm58, toc as t58 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Popover/index.md?type=frontmatter';
import { demoIndex as dmi58 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Popover/index.md?type=demo-index';
import { frontmatter as fm59, toc as t59 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/ProgressBar/index.md?type=frontmatter';
import { demoIndex as dmi59 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/ProgressBar/index.md?type=demo-index';
import { frontmatter as fm60, toc as t60 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Radio/index.md?type=frontmatter';
import { demoIndex as dmi60 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Radio/index.md?type=demo-index';
import { frontmatter as fm61, toc as t61 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Search/index.md?type=frontmatter';
import { demoIndex as dmi61 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Search/index.md?type=demo-index';
import { frontmatter as fm62, toc as t62 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Segmented/index.md?type=frontmatter';
import { demoIndex as dmi62 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Segmented/index.md?type=demo-index';
import { frontmatter as fm63, toc as t63 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Select/index.md?type=frontmatter';
import { demoIndex as dmi63 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Select/index.md?type=demo-index';
import { frontmatter as fm64, toc as t64 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Skeleton/index.md?type=frontmatter';
import { demoIndex as dmi64 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Skeleton/index.md?type=demo-index';
import { frontmatter as fm65, toc as t65 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Slider/index.md?type=frontmatter';
import { demoIndex as dmi65 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Slider/index.md?type=demo-index';
import { frontmatter as fm66, toc as t66 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Sparkline/index.md?type=frontmatter';
import { demoIndex as dmi66 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Sparkline/index.md?type=demo-index';
import { frontmatter as fm67, toc as t67 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Spinner/index.md?type=frontmatter';
import { demoIndex as dmi67 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Spinner/index.md?type=demo-index';
import { frontmatter as fm68, toc as t68 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Splitter/index.md?type=frontmatter';
import { demoIndex as dmi68 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Splitter/index.md?type=demo-index';
import { frontmatter as fm69, toc as t69 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Stat/index.md?type=frontmatter';
import { demoIndex as dmi69 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Stat/index.md?type=demo-index';
import { frontmatter as fm70, toc as t70 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Stepper/index.md?type=frontmatter';
import { demoIndex as dmi70 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Stepper/index.md?type=demo-index';
import { frontmatter as fm71, toc as t71 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Switch/index.md?type=frontmatter';
import { demoIndex as dmi71 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Switch/index.md?type=demo-index';
import { frontmatter as fm72, toc as t72 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/TablePagination/index.md?type=frontmatter';
import { demoIndex as dmi72 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/TablePagination/index.md?type=demo-index';
import { frontmatter as fm73, toc as t73 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Tabs/index.md?type=frontmatter';
import { demoIndex as dmi73 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Tabs/index.md?type=demo-index';
import { frontmatter as fm74, toc as t74 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Tag/index.md?type=frontmatter';
import { demoIndex as dmi74 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Tag/index.md?type=demo-index';
import { frontmatter as fm75, toc as t75 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/TagInput/index.md?type=frontmatter';
import { demoIndex as dmi75 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/TagInput/index.md?type=demo-index';
import { frontmatter as fm76, toc as t76 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Textarea/index.md?type=frontmatter';
import { demoIndex as dmi76 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Textarea/index.md?type=demo-index';
import { frontmatter as fm77, toc as t77 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Timeline/index.md?type=frontmatter';
import { demoIndex as dmi77 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Timeline/index.md?type=demo-index';
import { frontmatter as fm78, toc as t78 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Toast/index.md?type=frontmatter';
import { demoIndex as dmi78 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Toast/index.md?type=demo-index';
import { frontmatter as fm79, toc as t79 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Tooltip/index.md?type=frontmatter';
import { demoIndex as dmi79 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Tooltip/index.md?type=demo-index';
import { frontmatter as fm80, toc as t80 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Tree/index.md?type=frontmatter';
import { demoIndex as dmi80 } from '/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Tree/index.md?type=demo-index';

export const filesMeta = {
  'index': {
    frontmatter: fm0,
    toc: t0,
  },
  'docs/getting-started/installation.en-US': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/getting-started/installation.en-US.md?type=text'),
  },
  'docs/getting-started/dark-mode.en-US': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/getting-started/dark-mode.en-US.md?type=text'),
  },
  'docs/getting-started/theming.en-US': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/getting-started/theming.en-US.md?type=text'),
  },
  'docs/getting-started/installation': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/getting-started/installation.md?type=text'),
  },
  'docs/getting-started/dark-mode': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/getting-started/dark-mode.md?type=text'),
  },
  'docs/getting-started/theming': {
    frontmatter: fm6,
    toc: t6,
    demoIndex: dmi6,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/getting-started/theming.md?type=text'),
  },
  'docs/tokens/typography.en-US': {
    frontmatter: fm7,
    toc: t7,
    demoIndex: dmi7,
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/typography.en-US.md?type=text'),
  },
  'docs/tokens/elevation.en-US': {
    frontmatter: fm8,
    toc: t8,
    demoIndex: dmi8,
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/elevation.en-US.md?type=text'),
  },
  'docs/tokens/overview.en-US': {
    frontmatter: fm9,
    toc: t9,
    demoIndex: dmi9,
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/overview.en-US.md?type=text'),
  },
  'docs/tokens/spacing.en-US': {
    frontmatter: fm10,
    toc: t10,
    demoIndex: dmi10,
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/spacing.en-US.md?type=text'),
  },
  'docs/tokens/motion.en-US': {
    frontmatter: fm11,
    toc: t11,
    demoIndex: dmi11,
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/motion.en-US.md?type=text'),
  },
  'docs/tokens/color.en-US': {
    frontmatter: fm12,
    toc: t12,
    demoIndex: dmi12,
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/color.en-US.md?type=text'),
  },
  'docs/tokens/typography': {
    frontmatter: fm13,
    toc: t13,
    demoIndex: dmi13,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/typography.md?type=text'),
  },
  'docs/tokens/elevation': {
    frontmatter: fm14,
    toc: t14,
    demoIndex: dmi14,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/elevation.md?type=text'),
  },
  'docs/tokens/overview': {
    frontmatter: fm15,
    toc: t15,
    demoIndex: dmi15,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/overview.md?type=text'),
  },
  'docs/tokens/spacing': {
    frontmatter: fm16,
    toc: t16,
    demoIndex: dmi16,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/spacing.md?type=text'),
  },
  'docs/tokens/motion': {
    frontmatter: fm17,
    toc: t17,
    demoIndex: dmi17,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/motion.md?type=text'),
  },
  'docs/tokens/color': {
    frontmatter: fm18,
    toc: t18,
    demoIndex: dmi18,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/tokens/color.md?type=text'),
  },
  'docs/index.en-US': {
    frontmatter: fm19,
    toc: t19,
    demoIndex: dmi19,
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/index.en-US.md?type=text'),
  },
  'docs/index': {
    frontmatter: fm20,
    toc: t20,
    demoIndex: dmi20,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/docs/index.md?type=text'),
  },
  'components/Accordion/index': {
    frontmatter: fm21,
    toc: t21,
    demoIndex: dmi21,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Accordion/index.md?type=text'),
  },
  'components/Alert/index': {
    frontmatter: fm22,
    toc: t22,
    demoIndex: dmi22,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Alert/index.md?type=text'),
  },
  'components/AlertDialog/index': {
    frontmatter: fm23,
    toc: t23,
    demoIndex: dmi23,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/AlertDialog/index.md?type=text'),
  },
  'components/Avatar/index': {
    frontmatter: fm24,
    toc: t24,
    demoIndex: dmi24,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Avatar/index.md?type=text'),
  },
  'components/Badge/index': {
    frontmatter: fm25,
    toc: t25,
    demoIndex: dmi25,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Badge/index.md?type=text'),
  },
  'components/Banner/index': {
    frontmatter: fm26,
    toc: t26,
    demoIndex: dmi26,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Banner/index.md?type=text'),
  },
  'components/Breadcrumb/index': {
    frontmatter: fm27,
    toc: t27,
    demoIndex: dmi27,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Breadcrumb/index.md?type=text'),
  },
  'components/Button/index': {
    frontmatter: fm28,
    toc: t28,
    demoIndex: dmi28,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Button/index.md?type=text'),
  },
  'components/Calendar/index': {
    frontmatter: fm29,
    toc: t29,
    demoIndex: dmi29,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Calendar/index.md?type=text'),
  },
  'components/Card/index': {
    frontmatter: fm30,
    toc: t30,
    demoIndex: dmi30,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Card/index.md?type=text'),
  },
  'components/Checkbox/index': {
    frontmatter: fm31,
    toc: t31,
    demoIndex: dmi31,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Checkbox/index.md?type=text'),
  },
  'components/CodeBlock/index': {
    frontmatter: fm32,
    toc: t32,
    demoIndex: dmi32,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/CodeBlock/index.md?type=text'),
  },
  'components/Combobox/index': {
    frontmatter: fm33,
    toc: t33,
    demoIndex: dmi33,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Combobox/index.md?type=text'),
  },
  'components/CommandPalette/index': {
    frontmatter: fm34,
    toc: t34,
    demoIndex: dmi34,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/CommandPalette/index.md?type=text'),
  },
  'components/ContextMenu/index': {
    frontmatter: fm35,
    toc: t35,
    demoIndex: dmi35,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/ContextMenu/index.md?type=text'),
  },
  'components/DataTable/index': {
    frontmatter: fm36,
    toc: t36,
    demoIndex: dmi36,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/DataTable/index.md?type=text'),
  },
  'components/DateRangePicker/index': {
    frontmatter: fm37,
    toc: t37,
    demoIndex: dmi37,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/DateRangePicker/index.md?type=text'),
  },
  'components/Dialog/index': {
    frontmatter: fm38,
    toc: t38,
    demoIndex: dmi38,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Dialog/index.md?type=text'),
  },
  'components/Divider/index': {
    frontmatter: fm39,
    toc: t39,
    demoIndex: dmi39,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Divider/index.md?type=text'),
  },
  'components/Drawer/index': {
    frontmatter: fm40,
    toc: t40,
    demoIndex: dmi40,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Drawer/index.md?type=text'),
  },
  'components/DropdownMenu/index': {
    frontmatter: fm41,
    toc: t41,
    demoIndex: dmi41,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/DropdownMenu/index.md?type=text'),
  },
  'components/EmptyState/index': {
    frontmatter: fm42,
    toc: t42,
    demoIndex: dmi42,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/EmptyState/index.md?type=text'),
  },
  'components/FileUpload/index': {
    frontmatter: fm43,
    toc: t43,
    demoIndex: dmi43,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/FileUpload/index.md?type=text'),
  },
  'components/FilterChip/index': {
    frontmatter: fm44,
    toc: t44,
    demoIndex: dmi44,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/FilterChip/index.md?type=text'),
  },
  'components/Flex/index': {
    frontmatter: fm45,
    toc: t45,
    demoIndex: dmi45,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Flex/index.md?type=text'),
  },
  'components/FormField/index': {
    frontmatter: fm46,
    toc: t46,
    demoIndex: dmi46,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/FormField/index.md?type=text'),
  },
  'components/Grid/index': {
    frontmatter: fm47,
    toc: t47,
    demoIndex: dmi47,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Grid/index.md?type=text'),
  },
  'components/Input/index': {
    frontmatter: fm48,
    toc: t48,
    demoIndex: dmi48,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Input/index.md?type=text'),
  },
  'components/InputGroup/index': {
    frontmatter: fm49,
    toc: t49,
    demoIndex: dmi49,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/InputGroup/index.md?type=text'),
  },
  'components/Kbd/index': {
    frontmatter: fm50,
    toc: t50,
    demoIndex: dmi50,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Kbd/index.md?type=text'),
  },
  'components/KV/index': {
    frontmatter: fm51,
    toc: t51,
    demoIndex: dmi51,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/KV/index.md?type=text'),
  },
  'components/Label/index': {
    frontmatter: fm52,
    toc: t52,
    demoIndex: dmi52,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Label/index.md?type=text'),
  },
  'components/List/index': {
    frontmatter: fm53,
    toc: t53,
    demoIndex: dmi53,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/List/index.md?type=text'),
  },
  'components/Menubar/index': {
    frontmatter: fm54,
    toc: t54,
    demoIndex: dmi54,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Menubar/index.md?type=text'),
  },
  'components/MultiSelect/index': {
    frontmatter: fm55,
    toc: t55,
    demoIndex: dmi55,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/MultiSelect/index.md?type=text'),
  },
  'components/NavMenu/index': {
    frontmatter: fm56,
    toc: t56,
    demoIndex: dmi56,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/NavMenu/index.md?type=text'),
  },
  'components/NumberInput/index': {
    frontmatter: fm57,
    toc: t57,
    demoIndex: dmi57,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/NumberInput/index.md?type=text'),
  },
  'components/Popover/index': {
    frontmatter: fm58,
    toc: t58,
    demoIndex: dmi58,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Popover/index.md?type=text'),
  },
  'components/ProgressBar/index': {
    frontmatter: fm59,
    toc: t59,
    demoIndex: dmi59,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/ProgressBar/index.md?type=text'),
  },
  'components/Radio/index': {
    frontmatter: fm60,
    toc: t60,
    demoIndex: dmi60,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Radio/index.md?type=text'),
  },
  'components/Search/index': {
    frontmatter: fm61,
    toc: t61,
    demoIndex: dmi61,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Search/index.md?type=text'),
  },
  'components/Segmented/index': {
    frontmatter: fm62,
    toc: t62,
    demoIndex: dmi62,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Segmented/index.md?type=text'),
  },
  'components/Select/index': {
    frontmatter: fm63,
    toc: t63,
    demoIndex: dmi63,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Select/index.md?type=text'),
  },
  'components/Skeleton/index': {
    frontmatter: fm64,
    toc: t64,
    demoIndex: dmi64,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Skeleton/index.md?type=text'),
  },
  'components/Slider/index': {
    frontmatter: fm65,
    toc: t65,
    demoIndex: dmi65,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Slider/index.md?type=text'),
  },
  'components/Sparkline/index': {
    frontmatter: fm66,
    toc: t66,
    demoIndex: dmi66,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Sparkline/index.md?type=text'),
  },
  'components/Spinner/index': {
    frontmatter: fm67,
    toc: t67,
    demoIndex: dmi67,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Spinner/index.md?type=text'),
  },
  'components/Splitter/index': {
    frontmatter: fm68,
    toc: t68,
    demoIndex: dmi68,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Splitter/index.md?type=text'),
  },
  'components/Stat/index': {
    frontmatter: fm69,
    toc: t69,
    demoIndex: dmi69,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Stat/index.md?type=text'),
  },
  'components/Stepper/index': {
    frontmatter: fm70,
    toc: t70,
    demoIndex: dmi70,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Stepper/index.md?type=text'),
  },
  'components/Switch/index': {
    frontmatter: fm71,
    toc: t71,
    demoIndex: dmi71,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Switch/index.md?type=text'),
  },
  'components/TablePagination/index': {
    frontmatter: fm72,
    toc: t72,
    demoIndex: dmi72,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/TablePagination/index.md?type=text'),
  },
  'components/Tabs/index': {
    frontmatter: fm73,
    toc: t73,
    demoIndex: dmi73,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Tabs/index.md?type=text'),
  },
  'components/Tag/index': {
    frontmatter: fm74,
    toc: t74,
    demoIndex: dmi74,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Tag/index.md?type=text'),
  },
  'components/TagInput/index': {
    frontmatter: fm75,
    toc: t75,
    demoIndex: dmi75,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/TagInput/index.md?type=text'),
  },
  'components/Textarea/index': {
    frontmatter: fm76,
    toc: t76,
    demoIndex: dmi76,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Textarea/index.md?type=text'),
  },
  'components/Timeline/index': {
    frontmatter: fm77,
    toc: t77,
    demoIndex: dmi77,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Timeline/index.md?type=text'),
  },
  'components/Toast/index': {
    frontmatter: fm78,
    toc: t78,
    demoIndex: dmi78,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Toast/index.md?type=text'),
  },
  'components/Tooltip/index': {
    frontmatter: fm79,
    toc: t79,
    demoIndex: dmi79,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Tooltip/index.md?type=text'),
  },
  'components/Tree/index': {
    frontmatter: fm80,
    toc: t80,
    demoIndex: dmi80,
    textGetter: () => import(/* webpackChunkName: "meta__" */'/Users/dark/WebstormProjects/talon-sandbox-ui/packages/react/src/components/Tree/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
