// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import nprogress from '/Users/dark/WebstormProjects/talon-sandbox-ui/node_modules/.pnpm/nprogress@0.2.0/node_modules/nprogress';
import './nprogress.css';
import UserLoading from '/Users/dark/WebstormProjects/talon-sandbox-ui/node_modules/.pnpm/dumi@2.4.28_@babel+core@7.29.0_@swc+helpers@0.5.15_@types+node@22.19.19_@types+react@18.3.29__rencsaypkbx6uqm5i5qrjjixra/node_modules/dumi/dist/client/pages/Loading';
import React, { useLayoutEffect, type FC } from 'react';
import { useSiteData } from 'dumi';

const DumiLoading: FC = () => {
  const { setLoading } = useSiteData();

  useLayoutEffect(() => {
    setLoading(true);
    nprogress.start();

    return () => {
      setLoading(false);
      nprogress.done();
    }
  }, []);

  return <UserLoading />
}

export default DumiLoading;
