// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/dark/WebstormProjects/talon-sandbox-ui/node_modules/.pnpm/dumi@2.4.28_@babel+core@7.29.0_@swc+helpers@0.5.15_@types+node@22.19.19_@types+react@18.3.29__rencsaypkbx6uqm5i5qrjjixra/node_modules/dumi/theme-default/builtins/SourceCode/index.js';
