// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React, { useState, useEffect, useRef } from 'react';
import { useOutlet, history } from 'dumi';
import { warning } from '/Users/dark/WebstormProjects/talon-sandbox-ui/node_modules/.pnpm/rc-util@5.44.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/rc-util';
import { SiteContext, type ISiteContext } from '/Users/dark/WebstormProjects/talon-sandbox-ui/node_modules/.pnpm/dumi@2.4.28_@babel+core@7.29.0_@swc+helpers@0.5.15_@types+node@22.19.19_@types+react@18.3.29__rencsaypkbx6uqm5i5qrjjixra/node_modules/dumi/dist/client/theme-api/context.js';
import { components } from '../meta/atoms';
import { locales } from '../locales/config';



const entryExports = {
};

// Static content
const pkg = {"name":"@talon-sandbox/docs","version":"0.0.0"};
const historyType = "browser";
const hostname = undefined;
const themeConfig = {"title":"Talon Sandbox UI","footer":"MIT Licensed · Talon Sandbox Contributors","prefersColor":{"default":"auto","switch":true},"nprogress":true,"lastUpdated":true,"name":"Talon Sandbox UI","logo":false,"nav":{"zh-CN":[{"title":"组件","link":"/components/button"},{"title":"Tokens","link":"/tokens/overview"},{"title":"GitHub","link":"https://github.com/talon-org/talon-sandbox-ui"}],"en-US":[{"title":"Components","link":"/en-US/components/button"},{"title":"Tokens","link":"/en-US/tokens/overview"},{"title":"GitHub","link":"https://github.com/talon-org/talon-sandbox-ui"}]},"socialLinks":{"github":"https://github.com/talon-org/talon-sandbox-ui"}};
const _2_level_nav_available = true;

export default function DumiContextWrapper() {
  const outlet = useOutlet();
  const [loading, setLoading] = useState(false);
  const prev = useRef(history.location.pathname);

  useEffect(() => {
    return history.listen((next) => {
      if (next.location.pathname !== prev.current) {
        prev.current = next.location.pathname;

        // scroll to top when route changed
        document.documentElement.scrollTo(0, 0);
      }
    });
  }, []);

  const context: ISiteContext = React.useMemo(() => {
    const ctx = {
      pkg,
      historyType,
      entryExports,
      demos: null,
      components,
      locales,
      loading,
      setLoading,
      hostname,
      themeConfig,
      _2_level_nav_available,
    };

    // Proxy do not warning since `Object.keys` will get nothing to loop
    Object.defineProperty(ctx, 'demos', {
      get: () => {
        warning(false, '`demos` return empty in latest version, please use `useDemo` instead.');
        return {};
      },
    });

    return ctx;
  }, [
    pkg,
    historyType,
    entryExports,
    components,
    locales,
    loading,
    setLoading,
    hostname,
    themeConfig,
    _2_level_nav_available,
  ]);

  return (
    <SiteContext.Provider value={context}>
      {outlet}
    </SiteContext.Provider>
  );
}
