// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/dark/WebstormProjects/talon-sandbox-ui/apps/docs/node_modules/dumi-theme-antd/dist/slots/NotFound/index.js';
